### ISSUE TITLE
It causes session id to be different for every request

### ISSUE THREAD

**Issue by H0w4rd** [rootpd/nette-sentry#5]
I have a problem with this extension. It causes that I can't login to my web app. I was trying to figure it out, I discovered, that session id is different for every request, this extension somehow causes it, so the session is being forgotten after every request. When I comment out this extension in neon file, everything works as usual.
There are no PHP errors in any log folder. I use the latest stable Nette and PHP 7.4.
I don't know how to describe this problem more. I will try to explore your code and will get back at you if I discover something.
Otherwise it works, it sends messages to our Sentry.
But only causes described session mess.
Can you help me somehow? Can I provide more info?

**Comment by rootpd** [comment]
Hi. That's weird, we didn't encounter this kind of issue yet (and we do login to our app too).

The best would be to provide a repository or a couple of snippets with minimal application so I can replicate the issue if that's possible. Maybe start with https://github.com/nette/sandbox, add the extension, logic you use for logging in and see what happens?

**Comment by H0w4rd** [comment]
It works in nette sandbox, hmm. There must be something in our app :(
Session id always changes upon login and I end up back on the login page.

**Comment by H0w4rd** [comment]
I have just discovered that this line in our BasePresenter causes it
`$this->user->getStorage()->setNamespace('Admin');`
But I don't know why.

**Comment by H0w4rd** [comment]
Please is it possible to do anything with it?

**Comment by rootpd** [comment]
Hopefully fixed via @martenb PR #7, tagged as version `1.3.1`.
