### ISSUE TITLE
PHP 8.0.0 Compatibility 

### ISSUE THREAD

**Issue by rumcais** [rootpd/nette-sentry#6]
After running composer update in a nette project with PHP 8.0.0, I've got the following error:
` - rootpd/nette-sentry is locked to version 1.3.0 and an update of this package was not requested.
    - rootpd/nette-sentry 1.3.0 requires php ^7.2 -> your php version (8.0; overridden via config.platform, actual: 7.4.11) does not satisfy that requirement.`

**Comment by rootpd** [comment]
Handled in 1.4.0 via 242f54fdcdfafbcecbefb48f82f952244f075a2c.
